//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

//*****************************************************************************
//
//			PIN CONFIGURATIONS
//
//	GPIO PORTF PIN 	0 	= LCD RS
//	GPIO PORTE PIN 	0 	= LCD EN
//	GPIO PORTB PIN	7-0	= LCD D7-0
//	GPIO PORTD PIN 	0 	= LOAD CELL DOUT
//	GPIO PORTD PIN 	2 	= LOAD CELL CLK
//
//******************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "SmartBottleV1.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"
#include "driverlib/timer.h"
#include "driverlib/interrupt.h"
#include "inc/tm4c123gh6pm.h"


//*****************************************************************************
char inst = 'i';
char data = 'd';
int delay = 26667;
int i, j;
unsigned long mass = 0;
char buffer[32];

void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
		MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
		
		//
    // Enable pin PD0 for GPIOInput
    //
    MAP_GPIOPinTypeGPIOInput(GPIO_PORTD_BASE, GPIO_PIN_0);
	
		//
    // Enable pin PD2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTD_BASE, GPIO_PIN_2);
		
    //
    // Enable pin PB0 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_0);
    
		//
		// Enable pin PB1 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_1);

    //
    // Enable pin PB2 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_2);

    //
    // Enable pin PB3 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_3);

		//
    // Enable pin PB4 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_4);

    //
    // Enable pin PB5 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_5);
		    
		//
    // Enable pin PB6 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_6);

    //
    // Enable pin PB7 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTB_BASE, GPIO_PIN_7);

    //
    // Enable pin PE0 for GPIOOutput
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTE_BASE, GPIO_PIN_0);
		
    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;
	
		//
    //Now modify the configuration of the pins that we unlocked.
    //
    MAP_GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_0);
}


//Globally enable interrupts 
void IntGlobalEnable(void)
{
    __asm("    cpsie   i\n");
}

//Globally disable interrupts 
void IntGlobalDisable(void)
{
    __asm("    cpsid   i\n");
}

void
Interrupt_Init(void)
{
  NVIC_EN0_R |= 0x40000000;  		// enable interrupt 30 in NVIC (GPIOF)
	NVIC_PRI7_R &= 0x00E00000; 		// configure GPIOF interrupt priority as 0
	GPIO_PORTF_IM_R |= 0x11;   		// arm interrupt on PF0 and PF4
	GPIO_PORTF_IS_R &= ~0x11;     // PF0 and PF4 are edge-sensitive
  GPIO_PORTF_IBE_R &= ~0x11;   	// PF0 and PF4 not both edges trigger 
  GPIO_PORTF_IEV_R &= ~0x11;  	// PF0 and PF4 falling edge event
	IntGlobalEnable();        		// globally enable interrupt
}
void Timer0A_Init(unsigned long period)
{   
	//
  // Enable Peripheral Clocks 
  //
  SysCtlPeripheralEnable(SYSCTL_PERIPH_TIMER0);
  TimerConfigure(TIMER0_BASE, TIMER_CFG_PERIODIC); 		// configure for 32-bit timer mode
  TimerLoadSet(TIMER0_BASE, TIMER_A, period -1);      //reload value
	IntPrioritySet(INT_TIMER0A, 0x00);  	 // configure Timer0A interrupt priority as 0
  IntEnable(INT_TIMER0A);    				// enable interrupt 19 in NVIC (Timer0A)
	TimerIntEnable(TIMER0_BASE, TIMER_TIMA_TIMEOUT);      // arm timeout interrupt
  TimerEnable(TIMER0_BASE, TIMER_A);      // enable timer0A
}
void lcd_en(int n){
		GPIOPinWrite(GPIO_PORTE_BASE, GPIO_PIN_0, n);
}


void lcd_rs(char c){
		if(c == 'i'){
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_0, 0x0);
		}
		else if(c == 'd'){
				GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_0, 0x1);
		}
}


void lcd_clear(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x01);
		GPIO_PORTB_DATA_R = 0x01;
		SysCtlDelay(delay);
		lcd_en(0x0);
}
void lcd_entryDefaultSet(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x01);
		GPIO_PORTB_DATA_R = 0x01;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_home(){
		lcd_en(0x0);
		lcd_rs(inst);
		GPIO_PORTB_DATA_R = 0x02;
		SysCtlDelay(delay);
		lcd_en(0x1);
}

void lcd_displayOff(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = 0x08;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_displayOn(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = 0x0c;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_cursorOn(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = 0x0f;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_cursorOff(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = 0x12;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_shift(){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = 0x14;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_functionset(){
		lcd_en(0x0);
		lcd_rs(inst);
		GPIO_PORTB_DATA_R = 0x38; 
		SysCtlDelay(delay);
		lcd_en(0x1);
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_setAddr(int n){
		lcd_en(0x0);
		lcd_rs(inst);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = 0x80 + n;
		SysCtlDelay(delay);
		lcd_en(0x0);
}

void lcd_write(char c){
		int ascii = c;
		lcd_en(0x0);
		lcd_rs(data);
		lcd_en(0x1);
		GPIO_PORTB_DATA_R = ascii;
		SysCtlDelay(delay);
		lcd_en(0x0);
}
void lcd_type(char arr[32]){
		lcd_clear();
		SysCtlDelay(delay);
		lcd_home();
		
		for(i = 0; i < 32; i++){
				if(i == 16 || arr[i] == '\n'){
						lcd_setAddr(0x40);
				}
				
				if(arr[i] != '\0'){
						lcd_write(arr[i]);
				}
				else break;
		}
		
}
void lcd_init(){
		lcd_functionset();
		SysCtlDelay(delay);
		lcd_entryDefaultSet();
		SysCtlDelay(delay);
		lcd_cursorOn();
		SysCtlDelay(delay);
}


void pulseUp(){
		GPIO_PORTD_DATA_R |= 0x4;
}

void pulseDown(){
		GPIO_PORTD_DATA_R &= ~0x4;
}

bool lc_checkStatus(){
		bool status = false;
		if(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_0) == 0x0){
				status = true;
		}
		return status;
}
unsigned long lc_readMass(){
		unsigned long count = 0;
		
		while(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_0) == 0x1){
				lcd_type("not ready");
				SysCtlDelay(10000);
		}
		
		if(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_0) == 0x0){
				for(i = 0; i < 24; i++){
						pulseUp();
						count = count << 1;
						pulseDown();
						if(GPIOPinRead(GPIO_PORTD_BASE, GPIO_PIN_0) == 1) count++;
				}
				
				pulseUp();
				count = count ^ 0x800000;
				pulseDown();
		}
		
		return(count);
}

void lc_showMass(unsigned long in){
		unsigned int div = 0x800000;
		for(i = 0; i < 24; i++){
				if((in & div) == div){
						buffer[i] = '1';
				}
				else buffer[i] = '0';
				div = div / 0x02;
		}
		lcd_type(buffer);
}

//interrupt handler for Timer0A
void Timer0A_Handler(void){
	
		// acknowledge flag for Timer0A timeout
		TimerIntClear(TIMER0_BASE, TIMER_TIMA_TIMEOUT);
		
		lc_showMass(lc_readMass());
}

int main(void)
{
		int secs = 1;
		unsigned long period = secs * 10000000;
		
		SysCtlClockSet(SYSCTL_SYSDIV_20| SYSCTL_USE_PLL| SYSCTL_XTAL_16MHZ| SYSCTL_OSC_MAIN);
		
		//initialize the GPIO ports	
		PortFunctionInit();
		GPIO_PORTD_DATA_R &= 0x1;
		SysCtlDelay(10000000);
		
		lcd_init();
		SysCtlDelay(delay);
		
		lcd_type("Initializing...");	
		SysCtlDelay(1000000);
	
		Timer0A_Init(period);
		
		
		while(1)
    {
    }
}
